spin_manifest_version = 2

[application]
name = "fermyon"
version = "0.1.0"
authors = ["Agrima", "David", "Isabela"]
description = ""

[[trigger.http]]
route = "/basic-http"
component = "basic-http"

[component.basic-http]
source = "basic-http/dist/basic-http.wasm"
allowed_outbound_hosts = []

[component.basic-http.build]
command = "npm install && npm run build"
workdir = "basic-http"

[[trigger.http]]
route = "/key-value"
component = "key-value"

[component.key-value]
source = "key-value/dist/key-value.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]

[component.key-value.build]
command =  ["npm install", "npm run build"]
workdir = "key-value"
watch = ["src/**/*.ts"]

[variables]
kv_explorer_user = { required = true }
kv_explorer_password = { required = true }

[[trigger.http]]
component = "kv-explorer"
route = "/internal/kv-explorer/..."

[component.kv-explorer]
source = { url = "https://github.com/fermyon/spin-kv-explorer/releases/download/v0.10.0/spin-kv-explorer.wasm", digest = "sha256:65bc286f8315746d1beecd2430e178f539fa487ebf6520099daae09a35dbce1d" }
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
key_value_stores = ["default"]

[component.kv-explorer.variables]
kv_credentials = "{{ kv_explorer_user }}:{{ kv_explorer_password }}"

[[trigger.http]]
route = "/light-compute"
component = "light-compute"

[component.light-compute]
source = "light-compute/dist/light-compute.wasm"
allowed_outbound_hosts = []

[component.light-compute.build]
command = "npm install && npm run build"
workdir = "light-compute"

[[trigger.http]]
route = "/heavy-compute"
component = "heavy-compute"

[component.heavy-compute]
source = "heavy-compute/dist/heavy-compute.wasm"
allowed_outbound_hosts = []

[component.heavy-compute.build]
command = "npm install && npm run build"
workdir = "heavy-compute"

[[trigger.http]]
route = "/query-external"
component = "query-external"

[component.query-external]
source = "query-external/dist/query-external.wasm"
allowed_outbound_hosts = ["https://api.open-meteo.com"]

[component.query-external.build]
command = "npm install && npm run build"
workdir = "query-external"
