spin_manifest_version = 2

[application]
authors = ["Agrima Singh <agrima@student.chalmers.se>"]
description = ""
name = "query-external"
version = "0.1.0"

[[trigger.http]]
route = "/query-external"
component = "query-external"

[[trigger.http]]
route = "/..."
component = "query-external"  # Catch-all route

[component.query-external]
source = "dist/query-external.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://api.open-meteo.com"]

[component.query-external.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js"]

